name: Agent CLI Client CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e/agent-cli-client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Install Gauge
        run: |
          curl -sSfL https://downloads.gauge.org/stable | sh -s -- --location=/usr/local/bin
          gauge install java
          gauge --version

      - name: Build Kotlin code
        run: make build

      - name: Run Gauge tests
        run: make test

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: reports/
          retention-days: 30
