name: Build Example API

on:
  push:
    paths:
      - 'example-api/**'
      - '.github/workflows/build-example-api.yml'
  pull_request:
    paths:
      - 'example-api/**'
      - '.github/workflows/build-example-api.yml'

env:
  AWS_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            example-api/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('example-api/Cargo.lock') }}

      - name: Run tests
        run: |
          cd example-api
          cargo test

      - name: Build binary
        run: |
          cd example-api
          cargo build --release

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # TODO: Add this secret to GitHub repository settings
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.ref == 'refs/heads/main'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/agent/example-api:$IMAGE_TAG
          
          docker build -t $IMAGE_URI ./example-api
          docker push $IMAGE_URI
          
          echo "Built and pushed: $IMAGE_URI"